### ISSUE TITLE
support for German 

### ISSUE THREAD

**Issue by drford17** [Xaque8787/m3uparser#14]
Hi,

is it possible to support, I think UTF-8 or 16?,  to also have German "ä" ö" covered?
I end up with strange filenames due to the lack of support and if I use the replace env I am not able to scrape the content. 

Thank you

**Comment by Xaque8787** [comment]
Could you give me an example of what is happening here so I can understand the context better?

Are you saying a title that contains ä or ö characters in the providers m3u, when being parsed by the script is not maintaining those characters in the final output?

**Comment by drford17** [comment]
issue closed, was related to my smb config 
thanks for your prompt response

**Comment by drford17** [comment]
issue on samba config
