### ISSUE TITLE
scrub header help

### ISSUE THREAD

**Issue by drford17** [Xaque8787/m3uparser#15]
Hi,

I would have a question when it comes to the scrub header option. If I have the following example 

Adventure,Movie1
Comedy,Movie2
Horror,Movie3

How can I scrub "Adventure," and "Comedy,"

- SCRUB_HEADER="Comedy, Adventure, Horror" is keeping  the ","

Can you please help with the syntax?

Thank you very much

**Comment by Xaque8787** [comment]
Try putting a comma after horror as well like this

SCRUB_HEADER="Comedy, Adventure, Horror,"

Can you provide a example of the EXTINF line from the m3u file so I could help further diagnose the issue?

**Comment by Xaque8787** [comment]
> Hi,
> 
> I would have a question when it comes to the scrub header option. If I have the following example 
> 
> Adventure,Movie1
> Comedy,Movie2
> Horror,Movie3
> 
> How can I scrub "Adventure," and "Comedy,"
> 
> - SCRUB_HEADER="Comedy, Adventure, Horror" is keeping  the ","
> 
> Can you please help with the syntax?
> 
> Thank you very much
> 

Ok actually I see the issue you're having. We need to be able to escape the commas so they are treated in part of the scrub header value and not used as the seperator. I think I have a fix for this, and can push and update in a day or two.

**Comment by drford17** [comment]
thanks a lot for your fast reply again. Thats exactly the issue.

for reference:
#EXTINF:-1 tvg-name="Catch Me If You Can (2002)" tvg-logo="https://image.tmdb.org/tbJLrws4RmIw.jpg" group-title="Drama",Catch Me If You Can (2002)

**Comment by Xaque8787** [comment]
Already have a fix in place that will allow using \ to escape commas, just need to update a couple of other issues and I'll get that pushed soon. You'll need to repull the image when I do push it to dockerhub.

**Comment by Xaque8787** [comment]
> thanks a lot for your fast reply again. Thats exactly the issue.
> 
> for reference:
> #EXTINF:-1 tvg-name="Catch Me If You Can (2002)" tvg-logo="https://image.tmdb.org/tbJLrws4RmIw.jpg" group-title="Drama",Catch Me If You Can (2002)

Update has been pushed. You'll need to repull the image.

Your SCRUB_HEADER value should  look like this.

SCRUB_HEADER="Drama\\,, Horror\\,, Comedy\\,"

So the \\, escapes the comma and then you still use another non escaped comma to seperate the values.

**Comment by Xaque8787** [comment]
Want to also follow up with this, as I noticed in your example you have something like "Drama",Movie Title

So there are also " " that would need to be removed and captured by the scrub header value. If you're still having an issue with this after pulling the update, a current work around that should get this working is to do something like this, ensuring that the first and last scrub header terms are "dummy" values, as the script strips " from the begining and end of the dictionary of terms to remove when applying the scrub header.

So something like this should work to include " " in the dcrub header terms.

SCRUB_HEADER="dummyvalue, \\"Drama\\"\\,, \\"Horror\\"\\,, \\"Comedy\\"\\,, fakevalue"

**Comment by drford17** [comment]
yesss! thanks a lot! Everything is working as expected.

**Comment by pr0fsmith** [comment]
Hey I've tried the things above and they have worked but I'm still unable to scrub a few like anything with "Comedy," or "Documentary,".  There's also more but I won't put them all.  Here's my compose entry

```SCRUB_HEADER="dummyvalue, \"\,\", ;Family, Family, Family\,, \"\,24-7\", 24-7, Streams, ;, Action\,, Musical\,, Romance\,, Adventure\,, Biography\,, Action;, ;Action, ;Adventure, Adventure;, ;Comedy, Comedy;, \"Comedy\"\,, \"Crime\"\,, ;Drama, Drama;, ;Horror, Horror;, ;Sci-Fi, Sci-Fi;, ;Biography, Biography;, ;Crime, Crime;, Action\,, Animation, Short, Fantasy, Sport, \"Documnetary\"\,, fakevslue,"```

Here's an example of the strm file
```
root@jellyfin:/data/m3u/Movie_VOD/Documentary,The Geographies of DAR (2023)# cat 'Documentary,The Geographies of DAR (2023).strm'
https://thunderbolt-40gbps.com/movie/FyTcote5/oBNY79pD/900033680root@jellyfin:/data/m3u/Movie_VOD/Documentary,The Geographies of DAR (2023)
```

**Comment by pr0fsmith** [comment]
Nvm I got it working but just doing ```"\,, ;,"```.  That removed all the headers
