### ISSUE TITLE
No connection adapters were found

### ISSUE THREAD

**Issue by silentjay1980** [Xaque8787/m3uparser#17]
I keep getting this error whenever i try to run the container. ive tried a direct link to the m3u and also running it through my m3u editor first. here are the two urls ive tried with personal info redacted:

INFO - Error processing URL "https://opop.pro/xxxxxxxxxxxxx: No connection adapters were found for '"https://opop.pro/xxxxxxxxxxxxx'

and

https://www.torrentday.com/m3u.php?t=1&c=0&u=xxxxxxxx&s=xxxxxxxxx

i get the same error in both cases. ive tried changing the env variable BYPASS_HEADER to true as recommended elsewhere

my docker compose looks like this

m3uparser:
    container_name: m3uparser
    image: xaque87/m3uparser:latest
    environment:
      - PUID=1000
      - PGID=1000     
      - M3U_URL= "xxxxxxxx"
      - HOURS=12
      - BYPASS_HEADER=true
    volumes:
      - /volume1/Media/VOD:/usr/src/app/VODS
      - /volume1/Media/VOD:/usr/src/app/logs

and the log looks like this:

Creating new group 'm3ugroup'...

Creating new user 'm3uuser'...

Setting ownership and permissions...

Switching to user 'm3uuser' and running parser_script...

INFO - Skipping url header check.

INFO - Error processing URL ": No connection adapters were found for '"'

INFO - All URLs processed.

INFO - All files have been combined into /usr/src/app/m3u_file.m3u

INFO - Moving livetv.m3u

INFO - Removed existing file at /usr/src/app/VODS/Live_TV/livetv.m3u

INFO - Moved /usr/src/app/livetv.m3u to /usr/src/app/VODS/Live_TV

INFO - Removed file: /usr/src/app/m3u_file.m3u

INFO - Removed folder and its contents: /usr/src/app/Movie_VOD

INFO - Removed folder and its contents: /usr/src/app/TV_VOD

INFO - Removed folder and its contents: /usr/src/app/Unsorted_VOD

INFO - Removed folder and its contents: /usr/src/app/VODS/Unsorted_VOD

INFO - 

INFO - Total number of errors:

INFO - 0

INFO - 

INFO - Number of movies parsed =

INFO - 0

INFO - Number of episodes parsed =

INFO - 0

INFO - Number of unsorted entries parsed =

INFO - 0

INFO - Number of live TV channels parsed =

INFO - 0

INFO - Waiting for 43200 seconds before restarting...

**Comment by Xaque8787** [comment]
May be that your providers url format is not supported by this script, that last url format with .php and username and password is more than likely not going to work. The first two you posted don't contain enough info for me to fully diagnose what the issue may be. I can tell you to try and paste those urls in a browser and see what happens, if it immediately starts a download of the m3u file or not should give me an idea of what may be going on.

**Comment by silentjay1980** [comment]
Both urls download an m3u file. id be fine with sending you the opop url in full privately as i can just delete it once youre done testing it and change it.

**Comment by Xaque8787** [comment]
> Both urls download an m3u file. id be fine with sending you the opop url in full privately as i can just delete it once youre done testing it and change it. 

Before we do that, can you paste exactly what your compose file M3U_URL line looks like, redacting any sensitive information in the url, while at the same time keeping it as much intact to the original as possible? Could be a simple syntax error, like trailing whitespace within the quotes, or perhaps missing the https:// header.

Also does your username or password in the url contain a $

**Comment by silentjay1980** [comment]
m3uparser:
    container_name: m3uparser
    image: xaque87/m3uparser:latest
    environment:
      - PUID=1000
      - PGID=1000     
      - M3U_URL= "https://opop.pro/ekUuxxxxxunZ7"
      - HOURS=12
      - BYPASS_HEADER=true
    volumes:
      - /volume1/Media/VOD:/usr/src/app/VODS
      - /volume1/Media/VOD:/usr/src/app/logs


m3uparser:
    container_name: m3uparser
    image: xaque87/m3uparser:latest
    environment:
      - PUID=1000
      - PGID=1000     
      - M3U_URL= "https://www.torrentday.com/m3u.php?t=1&c=1&u=xxx7634&s=xxxm9lvObS"
      - HOURS=12
      - BYPASS_HEADER=true
    volumes:
      - /volume1/Media/VOD:/usr/src/app/VODS
      - /volume1/Media/VOD:/usr/src/app/logs

**Comment by silentjay1980** [comment]
im realizing my mistake here. i removed the " " and it worked. my fault. thanks for indulging me
